. $HOME/.nix-profile/etc/profile.d/nix.sh
export NIX_PATH=$HOME/.nix-defexpr/channels:$HOME/.nix-defexpr/channels:$HOME/.nix-defexpr/channels
export PATH=$PATH:/home/leo/Code/personal/home-manager/bin
setxkbmap -option caps:escape
alias ls="ls --color=auto"
eval "$(dircolors)"
export LS_COLORS

if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/key-bindings.bash"
  source "$(fzf-share)/completion.bash"
fi
